version: '3.7'

services:
  client:
    image: nginx:stable-alpine3.19-slim
    container_name: webStockSoporte
    volumes:
      - ./app/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - red-gane-int

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: api_bod_stock
    image: api_bod_stock:v1
    networks:
      - red-gane-int
    environment:
      - TZ=America/Bogota
      
networks:
  red-gane-int:
    external: true